FROM python:3.10.12-slim
RUN mkdir -p /opt/app
RUN mkdir -p /opt/app/model
WORKDIR /opt/app
ADD data data
COPY train.py train.py
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt